# Generated by Django 5.2.10 on 2026-04-17 14:42

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('scoring', '0002_alter_applicationstatus_id_alter_employmenttype_id_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE scoring_systemdecision ALTER COLUMN id TYPE integer USING id::integer;',
            reverse_sql='ALTER TABLE scoring_systemdecision ALTER COLUMN id TYPE bigint;'
        ),
        migrations.RunSQL(
            sql='ALTER TABLE scoring_employmenttype ALTER COLUMN id TYPE integer USING id::integer;',
            reverse_sql='ALTER TABLE scoring_employmenttype ALTER COLUMN id TYPE bigint;'
        ),
        migrations.RunSQL(
            sql='ALTER TABLE scoring_scoringresult ALTER COLUMN id TYPE integer USING id::integer;',
            reverse_sql='ALTER TABLE scoring_scoringresult ALTER COLUMN id TYPE bigint;'
        ),
        migrations.RunSQL(
            sql='ALTER TABLE clients_clientdata ALTER COLUMN id TYPE integer USING id::integer;',
            reverse_sql='ALTER TABLE clients_clientdata ALTER COLUMN id TYPE bigint;'
        ),
        migrations.RunSQL(
            sql="SELECT setval('scoring_systemdecision_id_seq', (SELECT MAX(id) FROM scoring_systemdecision));",
            reverse_sql=''
        ),
        migrations.RunSQL(
            sql="SELECT setval('scoring_employmenttype_id_seq', (SELECT MAX(id) FROM scoring_employmenttype));",
            reverse_sql=''
        ),
        migrations.RunSQL(
            sql="SELECT setval('scoring_scoringresult_id_seq', (SELECT MAX(id) FROM scoring_scoringresult));",
            reverse_sql=''
        ),
        migrations.RunSQL(
            sql="SELECT setval('clients_clientdata_id_seq', (SELECT MAX(id) FROM clients_clientdata));",
            reverse_sql=''
        ),
    ]