# Generated by Django 5.2.10 on 2026-04-17 15:12

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('scoring', '0003_auto_20260417_1742'),
    ]

    operations = [
        migrations.DeleteModel('ScoringResult'),
    ]