# Generated by Django 5.2.10 on 2026-01-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pre_registered',
            field=models.BooleanField(default=True, help_text='Сотрудник добавлен администратором, но еще не завершил регистрацию', verbose_name='Предварительная регистрация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
