# Generated by Django 5.2.10 on 2026-03-16 19:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_clientdata_employment_type'),
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_num', models.CharField(max_length=20, unique=True, verbose_name='Номер заявки')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Сумма кредита')),
                ('loan_term_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)], verbose_name='Срок кредита (мес)')),
                ('scoring_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Скоринговый балл')),
                ('scoring_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата скоринга')),
                ('probability_default', models.FloatField(blank=True, null=True, verbose_name='Вероятность дефолта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('top_factors', models.JSONField(blank=True, null=True, verbose_name='Ключевые факторы')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_applications', to='clients.client', verbose_name='Клиент')),
                ('client_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='clients.clientdata', verbose_name='Данные клиента на момент заявки')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('risk_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scoring.riskcategory', verbose_name='Категория риска')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoring.applicationstatus', verbose_name='Статус заявки')),
                ('system_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scoring.systemdecision', verbose_name='Решение системы')),
            ],
            options={
                'verbose_name': 'Кредитная заявка',
                'verbose_name_plural': 'Кредитные заявки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='credit_cred_client__ca2b7b_idx'), models.Index(fields=['app_num'], name='credit_cred_app_num_5a5879_idx')],
            },
        ),
    ]
