# Generated by Django 5.2.10 on 2026-03-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
