# Generated by Django 5.2.10 on 2026-03-04 12:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_series', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Серия паспорта должна состоять из 4 цифр')], verbose_name='Серия паспорта')),
                ('doc_number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Номер паспорта должен состоять из 6 цифр')], verbose_name='Номер паспорта')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone_num', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Некорректный номер телефона')], verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doc_series', 'doc_number'], name='clients_cli_doc_ser_b3a9ef_idx'), models.Index(fields=['last_name', 'first_name'], name='clients_cli_last_na_198e2f_idx'), models.Index(fields=['phone_num'], name='clients_cli_phone_n_b35345_idx'), models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx')],
                'unique_together': {('doc_series', 'doc_number')},
            },
        ),
    ]
