# Generated by Django 5.2.10 on 2026-03-16 19:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ежемесячный доход')),
                ('additional_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дополнительный доход')),
                ('employment_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стаж работы (лет)')),
                ('has_real_estate', models.BooleanField(default=False, verbose_name='Недвижимость')),
                ('has_car', models.BooleanField(default=False, verbose_name='Автомобиль')),
                ('has_business', models.BooleanField(default=False, verbose_name='Бизнес')),
                ('existing_credits_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество действующих кредитов')),
                ('total_monthly_payments', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ежемесячные платежи по кредитам')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Данные клиента',
                'verbose_name_plural': 'Данные клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
