# Generated by Django 5.2.10 on 2026-03-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientdata'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='employment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoring.employmenttype', verbose_name='Тип занятости'),
        ),
    ]
