# Generated by Django 5.2.10 on 2026-03-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
