# Generated by Django 5.2.10 on 2026-03-20 16:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_clientdata_id'),
        ('scoring', '0002_alter_applicationstatus_id_alter_employmenttype_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='acc_now_delinq',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Текущих просрочек'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='annual_inc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Годовой доход'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='bc_util',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Utilization по банковским картам (%)'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='collections_12_mths_ex_med',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Взысканий за 12 месяцев (без медицинских)'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='delinq_2yrs',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Просрочек за 2 года'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='dti',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Debt-to-Income (DTI, %)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='earliest_cr_line',
            field=models.DateField(blank=True, null=True, verbose_name='Дата первого кредита'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='emp_length',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='Стаж работы (лет)'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='home_ownership',
            field=models.CharField(choices=[('RENT', 'Аренда'), ('MORTGAGE', 'Ипотека'), ('OWN', 'Собственное'), ('OTHER', 'Другое')], default=0, max_length=20, verbose_name='Тип жилья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='inq_last_6mths',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Запросов в БКИ за 6 месяцев'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='installment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ежемесячный платеж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='loan_amnt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма кредита'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='mths_since_recent_inq',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Месяцев с последнего запроса в БКИ'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='percent_bc_gt_75',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% карт с utilization > 75%'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='pub_rec',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Публичных записей (банкротства и т.д.)'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='pub_rec_bankruptcies',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Банкротств'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='revol_util',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Revolving utilization (%)'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='tot_hi_cred_lim',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общий кредитный лимит'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='total_acc',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Всего кредитов (исторически)'),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='total_bal_ex_mort',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общий баланс без ипотеки'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='additional_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дополнительный доход'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='employment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scoring.employmenttype', verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='employment_years',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стаж работы (лет)'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ежемесячный доход'),
        ),
    ]
